name: Create temporary bazelrc file
description: |
  Create a temporary file that can be modified before being copied to the $HOME directory.

inputs:
  bazelrc_path:
    type: string
    description: The path to the original bazelrc file.
    required: true

outputs:
  bazelrc_tmp:
    description: The path to the temporary .bazelrc file.
    value: ${{ steps.create_bazelrc_tmp.bazelrc_tmp }}

runs:
  using: composite
  steps:
    - id: create_bazelrc_tmp
      shell: bash
      env:
        BAZELRC: ${{ inputs.bazelrc_path }}
      run: |
        bazelrc_tmp="${BAZELRC}.tmp"
        cp "${BAZELRC}" "${bazelrc_tmp}"
        echo "bazelrc_tmp=${bazelrc_tmp}" >> "$GITHUB_OUTPUT"
