name: Configure bazelrc file and copy to $HOME/.bazelrc

inputs:
  bazelrc_path:
    type: string
    description: The path to the bazelrc file to use as the starting point.
    default: '.bazelrc.ci'
  buildbuddy_api_key:
    type: string
    description: Buildbuddy API key

runs:
  using: composite
  steps:
    - id: create_bazelrc_tmp
      shell: bash
      env:
        BAZELRC: ${{ inputs.bazelrc_path }}
      run: |
        # DEBUG BEGIN
        set -x
        # DEBUG END
        bazelrc_tmp="${BAZELRC}.tmp"
        cp "${BAZELRC}" "${bazelrc_tmp}"
        echo "bazelrc_tmp=${bazelrc_tmp}" >> "$GITHUB_OUTPUT"

      # DO NOT MERGE!!!
      # TODO: Update with the correct tagged release.
    - uses: tweag/configure-bazel-remote-cache-auth@fix_output
      with:
        buildbuddy_api_key: ${{ inputs.buildbuddy_api_key }}
        bazelrc_path: ${{ steps.create_bazelrc_tmp.bazelrc_tmp }}

    - shell: bash
      env:
        BAZELRC_TMP: ${{ steps.create_bazelrc_tmp.bazelrc_tmp }}
      run: |
        cat >>"${BAZELRC_TMP}" <<EOF
        common --config=ci
        # no-op flag to avoid "ERROR: Config value 'ci' is not defined in any .rc file"
        common:ci --announce_rc=false
        EOF
        cp "${BAZELRC_TMP}" $HOME/.bazelrc
